### ISSUE TITLE
Emit web scrape results to queueing service

### ISSUE THREAD

**Issue by mattgawarecki** [EssDeeDee/safe-eats-etl#2]

**Comment by astrocaribe** [comment]
Kafka? There is a Python client that I can use.
https://github.com/confluentinc/confluent-kafka-python

We'd still want to persist to disk somewhere, right?

**Comment by mattgawarecki** [comment]
I'm actually going to close this issue for now. We should talk first, to get a more concrete idea of how it'll look.

**Comment by astrocaribe** [comment]
Fair enough...
